chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]

productSample = [
    "Chương trình đào tạo ngành Kinh tế công nghiệp kéo dài bao lâu?",
    "Ngành Kinh tế công nghiệp thuộc mã ngành nào?",
    "Tên tiếng Anh của ngành Kinh tế công nghiệp là gì?",
    "Cử nhân ngành này sẽ được đào tạo theo hình thức nào?",
    "Mục tiêu đào tạo của chuyên ngành Kế toán doanh nghiệp công nghiệp là gì?",
    "Người học sau khi tốt nghiệp sẽ đạt được những chuẩn đầu ra nào về kỹ năng cá nhân?",
    "Sinh viên tốt nghiệp có khả năng làm việc nhóm và sử dụng ngoại ngữ như thế nào?",
    "Học phần “Kế toán tài chính 1” nằm ở học kỳ nào và có bao nhiêu tín chỉ?",
    "Môn học nào là tiên quyết của học phần “Kế toán tài chính 2”?",
    "Sinh viên có thể lựa chọn học phần tự chọn nào trong học kỳ cuối nếu không làm khóa luận tốt nghiệp?"

]